"""Pairing API - 6-digit code device registration system.

Flow:
1. Admin generates a pairing code for a vessel (via Admin UI)
2. Edge device boots, technician enters cloud URL + 6-digit code
3. Device calls POST /api/devices/pair with code + device_id
4. Cloud validates code, creates LockerDevice record, returns API key + config
5. Device stores API key locally, starts syncing events
"""

import logging
from datetime import datetime
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.orm import selectinload
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models.device import LockerDevice
from app.models.pairing import PairingCode
from app.models.fleet import Vessel, Fleet
from app.models.company import Company
from app.models.product import Product, MixingRecipe
from app.models.maintenance import MaintenanceChart
from app.api.events import verify_device_api_key

logger = logging.getLogger("smartlocker.pairing")

router = APIRouter(prefix="/api/devices", tags=["pairing"])


# ---- Schemas ----

class PairRequest(BaseModel):
    """Request from edge device to pair with cloud."""
    pairing_code: str  # 6-digit alphanumeric code
    device_id: str  # Edge device identifier (e.g., "LOCKER-DEV-001")
    device_name: Optional[str] = None
    software_version: Optional[str] = None


class PairResponse(BaseModel):
    """Response to edge device after successful pairing."""
    success: bool
    api_key: str  # The device must store this securely
    device_uuid: str  # Cloud UUID for this device
    vessel_name: str
    vessel_imo: Optional[str] = None
    company_name: str
    fleet_name: str
    config: dict  # Products, recipes, settings to download


class ConfigSyncResponse(BaseModel):
    """Full config payload for device to sync."""
    products: list
    recipes: list
    config_version: int


# ---- Endpoints ----

@router.post("/pair", response_model=PairResponse)
async def pair_device(
    request: PairRequest,
    db: AsyncSession = Depends(get_db),
):
    """
    Pair an edge device using a 6-digit code.

    This is the main endpoint called by SmartLocker devices on first boot.
    The code must have been pre-generated by an admin for a specific vessel.
    """
    # 1. Find and validate the pairing code
    code_upper = request.pairing_code.strip().upper()
    result = await db.execute(
        select(PairingCode)
        .where(PairingCode.code == code_upper)
        .options(
            selectinload(PairingCode.vessel)
        )
    )
    pairing = result.scalar_one_or_none()

    if not pairing:
        raise HTTPException(
            status_code=404,
            detail="Invalid pairing code. Check the code and try again."
        )

    if pairing.is_used:
        raise HTTPException(
            status_code=409,
            detail="This pairing code has already been used."
        )

    if datetime.utcnow() >= pairing.expires_at:
        raise HTTPException(
            status_code=410,
            detail="This pairing code has expired. Ask your admin for a new one."
        )

    # 2. Check if device_id is already registered
    existing = await db.execute(
        select(LockerDevice).where(LockerDevice.device_id == request.device_id)
    )
    if existing.scalar_one_or_none():
        raise HTTPException(
            status_code=409,
            detail=f"Device '{request.device_id}' is already registered."
        )

    # 3. Load vessel with fleet and company for response
    vessel_result = await db.execute(
        select(Vessel)
        .where(Vessel.id == pairing.vessel_id)
        .options(
            selectinload(Vessel.fleet)
            .selectinload(Fleet.company)
        )
    )
    vessel = vessel_result.scalar_one_or_none()
    if not vessel:
        raise HTTPException(status_code=500, detail="Vessel not found for this code.")

    # 4. Generate API key and create device record
    api_key = LockerDevice.generate_api_key()
    device = LockerDevice(
        vessel_id=pairing.vessel_id,
        device_id=request.device_id,
        api_key_hash=api_key,  # Plaintext for MVP; hash in production
        name=pairing.device_name or request.device_name or None,
        software_version=request.software_version,
        status="online",
        last_heartbeat=datetime.utcnow(),
        installed_at=datetime.utcnow(),
    )
    db.add(device)
    await db.flush()

    # 5. Mark pairing code as used
    pairing.is_used = True
    pairing.used_by_device_id = device.id
    pairing.used_at = datetime.utcnow()

    # 6. Load product catalog and recipes for initial sync
    products_result = await db.execute(
        select(Product).where(Product.is_active == True).order_by(Product.name)
    )
    products = products_result.scalars().all()

    recipes_result = await db.execute(
        select(MixingRecipe).where(MixingRecipe.is_active == True)
    )
    recipes = recipes_result.scalars().all()

    # Load maintenance chart for the vessel (if any)
    chart_data = None
    chart_result = await db.execute(
        select(MaintenanceChart)
        .where(MaintenanceChart.vessel_id == vessel.id)
        .order_by(MaintenanceChart.updated_at.desc())
    )
    chart = chart_result.scalar_one_or_none()
    if chart and chart.parsed_data:
        chart_data = chart.parsed_data

    # Build config payload
    config = {
        "products": [
            {
                "id": str(p.id),
                "ppg_code": p.ppg_code,
                "name": p.name,
                "product_type": p.product_type,
                "density_g_per_ml": p.density_g_per_ml,
                "pot_life_minutes": p.pot_life_minutes,
                "hazard_class": p.hazard_class,
                "can_sizes_ml": p.can_sizes_ml,
                "can_tare_weight_g": p.can_tare_weight_g,
            }
            for p in products
        ],
        "recipes": [
            {
                "id": str(r.id),
                "name": r.name,
                "base_product_id": str(r.base_product_id),
                "hardener_product_id": str(r.hardener_product_id),
                "ratio_base": r.ratio_base,
                "ratio_hardener": r.ratio_hardener,
                "tolerance_pct": r.tolerance_pct,
                "thinner_pct_brush": r.thinner_pct_brush,
                "thinner_pct_roller": r.thinner_pct_roller,
                "thinner_pct_spray": r.thinner_pct_spray,
                "recommended_thinner_id": str(r.recommended_thinner_id) if r.recommended_thinner_id else None,
                "pot_life_minutes": r.pot_life_minutes,
            }
            for r in recipes
        ],
        "config_version": 1,
        "slot_count": device.slot_count or 4,
        "sync_interval_seconds": 300,  # Sync every 5 minutes
        "heartbeat_interval_seconds": 60,
    }

    # Include maintenance chart if available
    if chart_data:
        config["maintenance_chart"] = chart_data

    return PairResponse(
        success=True,
        api_key=api_key,
        device_uuid=str(device.id),
        vessel_name=vessel.name,
        vessel_imo=vessel.imo_number,
        company_name=vessel.fleet.company.name if vessel.fleet else "Unknown",
        fleet_name=vessel.fleet.name if vessel.fleet else "Unknown",
        config=config,
    )


@router.get("/{device_id}/config")
async def get_device_config(
    device_id: str,
    device: LockerDevice = Depends(verify_device_api_key),
    db: AsyncSession = Depends(get_db),
):
    """
    Get latest config for a device (products, recipes, settings).
    Called periodically by edge devices to check for updates.
    """
    # Update heartbeat
    device.last_heartbeat = datetime.utcnow()
    device.status = "online"

    # Load catalog
    products_result = await db.execute(
        select(Product).where(Product.is_active == True).order_by(Product.name)
    )
    products = products_result.scalars().all()

    recipes_result = await db.execute(
        select(MixingRecipe).where(MixingRecipe.is_active == True)
    )
    recipes = recipes_result.scalars().all()

    # Load maintenance chart for the device's vessel
    chart_data = None
    if device.vessel_id:
        chart_result = await db.execute(
            select(MaintenanceChart)
            .where(MaintenanceChart.vessel_id == device.vessel_id)
            .order_by(MaintenanceChart.updated_at.desc())
        )
        chart = chart_result.scalar_one_or_none()
        if chart and chart.parsed_data:
            chart_data = chart.parsed_data

    response = {
        "config_version": device.config_version,
        "slot_count": device.slot_count or 4,
        "products": [
            {
                "id": str(p.id),
                "ppg_code": p.ppg_code,
                "name": p.name,
                "product_type": p.product_type,
                "density_g_per_ml": p.density_g_per_ml,
                "pot_life_minutes": p.pot_life_minutes,
                "hazard_class": p.hazard_class,
                "can_sizes_ml": p.can_sizes_ml,
                "can_tare_weight_g": p.can_tare_weight_g,
            }
            for p in products
        ],
        "recipes": [
            {
                "id": str(r.id),
                "name": r.name,
                "base_product_id": str(r.base_product_id),
                "hardener_product_id": str(r.hardener_product_id),
                "ratio_base": r.ratio_base,
                "ratio_hardener": r.ratio_hardener,
                "tolerance_pct": r.tolerance_pct,
                "thinner_pct_brush": r.thinner_pct_brush,
                "thinner_pct_roller": r.thinner_pct_roller,
                "thinner_pct_spray": r.thinner_pct_spray,
                "recommended_thinner_id": str(r.recommended_thinner_id) if r.recommended_thinner_id else None,
                "pot_life_minutes": r.pot_life_minutes,
            }
            for r in recipes
        ],
        "sync_interval_seconds": 300,
        "heartbeat_interval_seconds": 60,
    }

    # Include maintenance chart if available
    if chart_data:
        response["maintenance_chart"] = chart_data

    # If admin has set a new password for this device, include it (one-time delivery)
    if device.pending_admin_password:
        response["admin_password"] = device.pending_admin_password
        device.pending_admin_password = None  # Clear after sending

    # Deliver pending OTA update command
    if device.pending_update_version and device.update_status == "pending":
        response["update"] = {
            "version": device.pending_update_version,
            "branch": device.pending_update_branch or "master",
            "action": "update",
        }
        device.update_status = "downloading"
        await db.commit()
        logger.info(f"Update command delivered to {device.device_id}: v{device.pending_update_version}")

    return response
